# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        api_secure_area:
            pattern: ^/api
            stateless: false
            simple_preauth:
                authenticator: api_key_authenticator
            provider: api_key_user_provider


    access_control:
        - { path: ^/api, roles: ROLE_AUTHOR }