# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments:
            em: @doctrine.orm.default_entity_manager

    api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        public: false

